const INC_COUNTER = 'INC_COUNTER';
const DEC_COUNTER = 'DEC_COUNTER';
const ADD_COUNTER = 'ADD_COUNTER';
const SUB_COUNTER = 'SUB_COUNTER';

export {
  INC_COUNTER,
  DEC_COUNTER,
  ADD_COUNTER,
  SUB_COUNTER
}