// counter
const INC_COUNTER = 'INC_COUNTER';
const DEC_COUNTER = 'DEC_COUNTER';
const ADD_COUNTER = 'ADD_COUNTER';
const SUB_COUNTER = 'SUB_COUNTER';

// result
const STORE_RESULT = 'STORE_RESULT';
const DELETE_RESULT = 'DELETE_RESULT';

export {
  INC_COUNTER,
  DEC_COUNTER,
  ADD_COUNTER,
  SUB_COUNTER,
  STORE_RESULT,
  DELETE_RESULT
}